### ISSUE TITLE
Finding home without encoders

### ISSUE THREAD

**Issue by kulbir-ahluwalia** [FarmBot/farmbot-mqtt-py#13]
Hi, 

We have been trying to "find home" without using encoders. But even after setting the "Stop at home" and "Stop at Max" to ON,
the farmbot continues to move below 0 indefinitely.

The attached picture is for the Z axis, but it is the same for the X and Y axes as well. This is done using a headless farmbot without any encoders or motors attached to test our scripts without causing damage to the actual farmbot.

How can we get it to stop at the zero position when trying to find home?

![headless_farmbot_z_Axis_keeps_going_down](https://user-images.githubusercontent.com/55640820/179036587-959e6a89-bc95-46b1-9fad-b509b3a66b07.png)

We would appreciate your help in this regard.

Thank you so much!

Sincerely,
Kulbir

**Comment by gabrielburnworth** [comment]
The "find home" command is an automatic method that requires feedback such as encoders, so it can't be used without that feedback. For more information, see the [axis setup documentation page](https://software.farm.bot/docs/axis-setup). If you'd just like to set the home position, perhaps you'd find the "Manually set home" section on that page helpful, where usage of the "set home" command is described (which can be accessed via `bot.lua('rpc({kind="zero", args={axis="z"}})')` if using this library).
