### ISSUE TITLE
A quick and basic working GUI app using daemonized Farmbot listener

### ISSUE THREAD

**Issue by tmaziere** [FarmBot/farmbot-mqtt-py#6]
Comments and advice welcome! (is this a safe approach?)

It is based on `threading` and `wx`. 

https://gist.github.com/tmaziere/6b7e97a5d7fa628fda94bf2942b52ddf

**Comment by RickCarlino** [comment]
This is geat, thanks for sharing! Here's a screenshot for anyone watching this thread:

![image](https://user-images.githubusercontent.com/1388608/113434778-3270b200-93a7-11eb-95c4-e0ed429c68cf.png)
