### ISSUE TITLE
Ability to manage REST resources and execute sequences

### ISSUE THREAD

**Issue by WathikAhmed** [FarmBot/farmbot-mqtt-py#8]
Hi, this python  wrapper works well for me, but it seems that it dosent offer as much as the farmbotJS. Were you thinking of adding support on here for the Ability to execute an existing sequence and the full REST resource management. Thanks

**Comment by RickCarlino** [comment]
@WathikAhmed We have considered both in the past but have not started work on either. We will keep this in mind as we prioritize features and plan the roadmap. Thanks.

**Comment by WathikAhmed** [comment]
Awesome, Thanks.
