### ISSUE TITLE
NTH? Support for extra axis? A?

### ISSUE THREAD

**Issue by burk80** [FarmBot/farmbot-mqtt-py#9]
Adderad similar question in arduino bit

Would it be possible to add an extra axis?  A for example ?

In the cnc world .. you can add a rotary axis or similar to make a flat bed behave in a diffrent way .. 

By making this possible you could in theory make one gantry move between multiple beds with the help of a carriage systemin some way .. 

Regards
Marcus

**Comment by roryaronson** [comment]
Please see the comment here: https://github.com/FarmBot/farmbot-arduino-firmware/issues/164#issuecomment-1063334881
